### ISSUE TITLE
No puedo escribir en tu repo

### ISSUE THREAD

**Issue by sukuzhanay** [somozadev/Programacion-concurrente#1]
Marcos buen trabajo, en la portada donde está tu fotografía y luego de la universidad no se muestra correctamente, en el ataque al EburnOut la URL es incorrecta , por lo demás genial todo

**Comment by somozadev** [comment]
![image](https://user-images.githubusercontent.com/35799901/115562728-12058a80-a2b7-11eb-81b7-629ef4bbe797.png)
